Repository ruljin/CodersCamp2020.Project.TypeScript.YahtzeeGame, pull requests merged in 2021-01, with the labels that each got.

#2 Feature/yarn setup
  .editorconfig
  .eslintignore
  .eslintrc
  .gitattributes
  .gitignore
  .stylelintrc
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/releases/yarn-berry.cjs
  .yarnrc.yml
  CHANGELOG.md
  CONTRIBUTION.md
  jest.config.js
  package.json
  postcss.config.js
  src/components/sample/sample.scss
  src/components/sample/sample.spec.ts
  src/components/sample/sample.ts
  src/index.html
  src/index.ts
  src/style.scss
  tsconfig.json
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: enhancement

#3 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#5 Feature/html linter
  .htmlvalidate.json
  CHANGELOG.md
  package.json
  src/index.html
  src/index.ts
  yarn.lock
Labels: enhancement

#6 Feature/web component interface
  CHANGELOG.md
  src/common/WebComponent.ts
  src/components/sample/sample.spec.ts
  src/components/sample/sample.ts
  src/index.ts
Labels: enhancement

#7 Add info about gh-pages branch
  CONTRIBUTION.md
Labels: documentation

#9 Feature/adding background images
  CHANGELOG.md
  CONTRIBUTION.md
  src/assets/stol klasyczny.png
  src/assets/stol piracki.png
  src/assets/stol smoki.png
  src/assets/tablica punkty.png
  src/assets/tlo mobile.png
  src/assets/tlo.png
Labels: enhancement

#10 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#12 Fix dev server to work on every compter
  package.json
  yarn.lock
Labels: bug

#11 Feature/router setup
  CHANGELOG.md
  jest.config.js
  src/common/Router.spec.ts
  src/common/Router.ts
  src/common/WebComponent.spec.ts
  src/common/WebComponent.ts
  src/components/sample/sample.spec.ts
  src/components/sample/sample.ts
  src/index.html
  src/index.ts
Labels: enhancement

#13 Change event router functions to static
  src/common/Router.spec.ts
  src/common/Router.ts
  src/index.ts
Labels: bug

#14 Fix bug with refreshing page through router refresh listener
  src/common/Router.ts
Labels: bug

#15 Fix error with nonstatic function in router
  src/common/Router.ts
Labels: bug

#16 Feature/gh pages deploy
  .eslintrc
  CHANGELOG.md
  package.json
  src/common/Router.spec.ts
  src/common/Router.ts
  src/index.ts
  yarn.lock
Labels: enhancement

#18 Feature/rules
  CHANGELOG.md
  src/components/rules/rules.scss
  src/components/rules/rules.spec.ts
  src/components/rules/rules.ts
Labels: enhancement

#25 Fill changelog history
  CHANGELOG.md
Labels: documentation

#30 Configure github actions
  .github/workflows/superlinter.yml
  CHANGELOG.md
Labels: enhancement

#28 Feature/background
  .eslintrc
  .htmlvalidate.json
  CHANGELOG.md
  src/_reset.scss
  src/assets/dice-alternative.png
  src/assets/dice-mobile-alternative.png
  src/assets/dice-mobile.png
  src/assets/dice.png
  src/assets/points-board.png
  src/assets/table-classic.png
  src/assets/table-dragon.png
  src/assets/table-pirat.png
  src/assets/tlo mobile.png
  src/assets/tlo.png
  src/components/dice-background/dice-background.scss
  src/components/dice-background/dice-background.spec.ts
  src/components/dice-background/dice-background.ts
  src/components/logo/logo.spec.ts
  src/components/logo/logo.ts
  src/index.ts
  src/style.scss
Labels: enhancement

#34 Fix tests for dice-background component
  src/components/dice-background/dice-background.spec.ts
Labels: bug

#24 Feature/menu
  CHANGELOG.md
  src/components/reference/reference.scss
  src/components/reference/reference.spec.ts
  src/components/reference/reference.ts
Labels: enhancement
